[package]
name = "day-17"
version = "0.1.0"
authors = ["1u0 <7.prime+gh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
